version: '3'

services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - mysql # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      - SERVER_PORT=3001
      - MYSQL_USER=fake_news
      - MYSQL_PASSWD=fake_news
      - DB_URL=mysql
      - MYSQL_INITDB=fake_news
    networks:
      - backend

  mysql:
    image: mysql:5.7.28
    restart: always
    environment:
      - MYSQL_DATABASE=fake_news
      - MYSQL_USER=fake_news
      - MYSQL_PASSWORD=fake_news
      - MYSQL_ROOT_PASSWORD=fake_news
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./mysql:/var/lib/mysql
    stdin_open: true
    tty: true
    networks:
      - backend

networks:
  backend: